services:
  datajoint:
    image: datajoint/datajoint  # only works on amd64
    volumes:
      - /Volumes/jifu/code/dev:/home/dev
    env_file: .env
    ports:
      - 4444:8888


  dj-notebook:
    image: datajoint-jupyter:arm64
    volumes:
      - /Volumes/jifu/code/dev/notebooks:/home/jupyter
      - /Volumes/jifu/code/dev/datajoint-tests:/home/tests
      - /Volumes/voltage:/voltage
      - /Volumes/
    working_dir: /home/jupyter
    env_file: .env
    ports:
      - 4444:8888
    entrypoint:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=''
      - --no-browser
    command: bash -c "
      git clone https://github.com/lens-biophotonics/dcimg.git
      && pip3 install dcimg/ --no-dependencies \"
